[package]
version = "1.0.0"

title = "item engineering tool connector"

description="import projects from item engineering tool"

readme  = "docs/README.md"

repository = "https://github.com/mtw75/item_extension"

category = "manufacturing"

keywords = ["kit", "ipolog", "item", "synctwin"]

preview_image = "data/preview.png"

icon = "data/icons/item_logo.png" 

[dependencies]
"omni.kit.uiapp" = {}
"omni.services.client" = {}
"omni.services.transport.client.http_async" = {}
"omni.kit.asset_converter" = {}
"omni.kit.window.content_browser" = { }

[[python.module]]
name = "synctwin.item.connector"

[settings]
